# .streamlit/secrets.toml
groq_api_key = "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"
hf_token = "HF_TOKEN"
google_maps_key = "AIzaSyCVxQWEEhZx3WBDrFWzXTmVp9dvxy_S__c"

snowflake_account = "mp23362.canada-central.azure"
snowflake_user = "FLORA0122"
snowflake_password = "Animal@Trace123!"
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "ANIMAL_DB"
snowflake_schema = "INSIGHTS"
snowflake_role = "ANIMAL_APP_ROLE"

free_sounds_key = "ZtanxG1or7Ud6137qNIwqDrlvm6BaQ63OoHCC1E0"
