# .streamlit/secrets.toml
groq_api_key = "GROQ_API_KEY"
hf_token = "HF_TOKEN"
google_maps_key = "GOO_TOKEN"

snowflake_account = "ELVORXO-FX00525"
snowflake_user = "user"
snowflake_password = "password"
snowflake_warehouse = "NATURETRACE_WH"
snowflake_database = "NATURETRACE_DB"
snowflake_schema = "NATURETRACE_S"
