# .streamlit/secrets.toml
# NatureTrace - Animal Discovery Platform Configuration
# This is the consolidated secrets file for all API keys and configuration

# =============================================================================
# AI & Language Model APIs
# =============================================================================
# Groq AI API for intelligent comparison between recognition models
groq_api_key = "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"

# Hugging Face Token for model access
hf_token = "HF_TOKEN"

# =============================================================================
# Computer Vision APIs
# =============================================================================
# Azure Computer Vision API for enhanced animal recognition
AZURE_COMPUTER_VISION_ENDPOINT = "https://animaldetection.cognitiveservices.azure.com"
AZURE_COMPUTER_VISION_KEY = "4i8TqMldmqfQbDbIhAw2enJeixSp2QYFA1z0C7mAv8gINOQBOCWSJQQJ99BGACBsN54XJ3w3AAAFACOGEwkd"

# =============================================================================
# Google Services
# =============================================================================
# Google Maps API for location services and mapping
google_maps_key = "AIzaSyCVxQWEEhZx3WBDrFWzXTmVp9dvxy_S__c"

# =============================================================================
# Snowflake Database Configuration
# =============================================================================
snowflake_account = "mp23362.canada-central.azure"
snowflake_user = "FLORA0122"
snowflake_password = "Animal@Trace123!"
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "ANIMAL_DB"
snowflake_schema = "INSIGHTS"
snowflake_role = "ANIMAL_APP_ROLE"

# =============================================================================
# Sound & Audio APIs
# =============================================================================
# FreeSound.org API for animal sound data
# Note: The current API key is invalid/expired. To get a new one:
# 1. Go to https://freesound.org/
# 2. Create an account and log in
# 3. Go to https://freesound.org/apiv2/apply/
# 4. Apply for API access
# 5. Replace the key below when you receive it
# freesound_api_key = "ZtanxG1or7Ud6137qNIwqDrlvm6BaQ63OoHCC1E0"  # INVALID - needs replacement

# Additional Sound API Keys (add values if available)
# macaulay_api_key = "your_macaulay_key"      # Macaulay Library (Cornell Lab)
# xeno_canto_api_key = "your_xeno_canto_key"  # Xeno-canto bird sound database
